export const recipeData = [ //will modify to add recipes remotely later
  {
    title: "Spaghetti Bolognese",
    imageUrl: "https://www.errenskitchen.com/wp-content/uploads/2018/08/Spaghetti-Bolognese-1-3.jpg",
    cuisine: "Italian",
    ingredients: "spaghetti, ground beef, tomato sauce, onion, garlic",
    instructions: "1. Cook spaghetti according to package instructions. 2. Brown ground beef in a pan. 3. Add onion and garlic and cook until softened. 4. Add tomato sauce and simmer for 10 minutes. 5. Serve sauce over spaghetti.",
    cooking_time: "1 hour",
    serving_size: "5 servings",
  },
  {
    title: "Pad Kee Mao",
    imageUrl: "https://hot-thai-kitchen.com/wp-content/uploads/2021/07/pad-kee-mao-blog.jpg",
    cuisine: "Thai",
    ingredients: "rice noodles, shrimp, tofu, bean sprouts, eggs",
    instructions: "1. Soak rice noodles in cold water for 30 minutes. 2. Heat oil in a pan and cook shrimp until pink. 3. Add tofu, bean sprouts, and eggs and stir-fry for 2 minutes. 4. Drain noodles and add to the pan. 5. Add sauce and stir-fry for another 2 minutes. 6. Serve hot.",
    cooking_time: "1 hour",
    serving_size: "5 servings",
  },
  {
    title: "Chicken Tikka Masala",
    imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/06/chicken-tikka-masala.jpg",
    cuisine: "Indian",
    ingredients: "chicken, masalas, heavy whipping cream",
    instructions: "1. Soak rice noodles in cold water for 30 minutes. 2. Heat oil in a pan and cook shrimp until pink. 3. Add tofu, bean sprouts, and eggs and stir-fry for 2 minutes. 4. Drain noodles and add to the pan. 5. Add sauce and stir-fry for another 2 minutes. 6. Serve hot.",
    cooking_time: "1 hour",
  },
  {
    title: "Rajma Chawal",
    imageUrl: "https://www.secondrecipe.com/wp-content/uploads/2017/08/rajma-chawal-1.jpg",
    cuisine: "Indian",
    ingredients: "rajma, rice, masalas",
    instructions: "1. Soak rice noodles in cold water for 30 minutes. 2. Heat oil in a pan and cook shrimp until pink. 3. Add tofu, bean sprouts, and eggs and stir-fry for 2 minutes. 4. Drain noodles and add to the pan. 5. Add sauce and stir-fry for another 2 minutes. 6. Serve hot.",
    cooking_time: "1 hour",
    serving_size: "5 servings",
  },
  {
    title: "Chicken Chow Mein",
    imageUrl: "https://thebigmansworld.com/wp-content/uploads/2023/02/chicken-chow-mein-recipe.jpg",
    cuisine: "Chinese",
    ingredients: "chicken, noodles, vegetables",
    instructions: "1. Soak rice noodles in cold water for 30 minutes. 2. Heat oil in a pan and cook shrimp until pink. 3. Add tofu, bean sprouts, and eggs and stir-fry for 2 minutes. 4. Drain noodles and add to the pan. 5. Add sauce and stir-fry for another 2 minutes. 6. Serve hot.",
    cooking_time: "1 hour",
    serving_size: "5 servings",
  },
  {
    title: "California Roll",
    imageUrl: "https://www.simplyrecipes.com/thmb/EgyBYE---ytAEssbF2zQP5eyDds=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-California-Roll-LEAD-05-3c3a2fb4a9034e5c8cb34d6a24d9731e.jpg",
    cuisine: "Japanese",
    ingredients: "nori, rice, avocado, imitation crab",
    instructions: "1. Soak rice noodles in cold water for 30 minutes. 2. Heat oil in a pan and cook shrimp until pink. 3. Add tofu, bean sprouts, and eggs and stir-fry for 2 minutes. 4. Drain noodles and add to the pan. 5. Add sauce and stir-fry for another 2 minutes. 6. Serve hot.",
    cooking_time: "5 minutes",
    serving_size: "5 servings",
  },
];